// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyq9mJ4VP3Y2zZXd3s1GaEUkJFeuwBvM4',
    appId: '1:156217611135:web:75b4c70c26e9c7ed77c04a',
    messagingSenderId: '156217611135',
    projectId: 'notesuploder',
    authDomain: 'notesuploder.firebaseapp.com',
    storageBucket: 'notesuploder.appspot.com',
    measurementId: 'G-NCKD2VHCBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2YFkkv4PB__fxZFBFcd-vdi6vUNTA7o',
    appId: '1:156217611135:android:023b6b04a5148bcf77c04a',
    messagingSenderId: '156217611135',
    projectId: 'notesuploder',
    storageBucket: 'notesuploder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa62xEngP5VSZy3iuazipvSO3muVctbm0',
    appId: '1:156217611135:ios:b9637b4a8ecf8a9a77c04a',
    messagingSenderId: '156217611135',
    projectId: 'notesuploder',
    storageBucket: 'notesuploder.appspot.com',
    iosBundleId: 'com.example.notesTaking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa62xEngP5VSZy3iuazipvSO3muVctbm0',
    appId: '1:156217611135:ios:b0ed4e789a845d7577c04a',
    messagingSenderId: '156217611135',
    projectId: 'notesuploder',
    storageBucket: 'notesuploder.appspot.com',
    iosBundleId: 'com.example.notesTaking.RunnerTests',
  );
}
